{
 "title": "AirGradient",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    { "expr": "rco2", "legendFormat": "CO2" }
   ]
  },
  {
   "title": "Particulates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    { "expr": "pm01", "legendFormat": "PM01" },
    { "expr": "pm02", "legendFormat": "PM2.5" },
    { "expr": "pm10", "legendFormat": "PM10" }
   ]
  },
  {
   "title": "TVOC Index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "tvoc_index", "legendFormat": "TVOC" }
   ]
  },
  {
   "title": "PM003 count/dl",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "pm003_cnt", "legendFormat": "PM003 Count" }
   ]
  },
  {
   "title": "NOX Index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "nox_index", "legendFormat": "NOX" }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "atmp", "legendFormat": "Temperature" }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "rhum", "legendFormat": "Relative Humidity" }
   ]
  }
 ]
}